### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by kpjonsson** [mskcc/tempo#298]
These items need to be (documented) in the `docs` folder.
- [x] Landing page with ToC at https://github.com/mskcc/vaporware/tree/master/doc
- [x] How to run?
- [x] How to create inputs (#282)? What are acceptable inputs, etc?
- [x] Provenance of reference files (#57)
- [x] Provenance of annotation files (#57)
- [x] Pipeline flowchart (#283 )
    - [x] Tools, important parametets, etc.
- [x] Output structure, formats, etc.
- [x] Anything AWS related

What else needs to go on here?

There's a skeleton in the [`feature/documentation`](https://github.com/mskcc/vaporware/tree/feature/documentation/docs) branch.

**Running list of "user problems" reported:**
- [x] What is a pipeline?
- [x] Failure due to singularity image pull. Explain to users what's happening and how to "fix", i.e. run again
- [x] What are these crazy phrases? e.g
```
N E X T F L O W  ~  version 19.01.0
Launching `somatic.nf` [chaotic_descartes] - revision: b31726dc56
WARN: There's no process matching config selector: FastP
[warm up] executor > lsf
```
- [x] What does this warning mean? Did I break something? `WARN: There's no process matching config selector: FastP`
- [x] Clarify that duplicates are not kosher: https://github.com/mskcc/vaporware/issues/305
- [x] Explain how to debug the pipeline, motivated by: https://github.com/mskcc/vaporware/issues/410
