### ISSUE TITLE
Check user inputs / error handling

### ISSUE THREAD

**Issue by kpjonsson** [mskcc/tempo#398]
We should do some basic checking and handling of user inputs. I thought we could list them here and deal with them in an orderly fashion:

- [x] Exit execution if `-profile` is not given.
- [x] Exit execution if both WES and WGS provided as inputs. _Done by @sivkovic in #400_.
- [x] Exit with warning if mixed assay/target types for the same sample.
- [ ] Check that sample mapping and pairing contains all common samples (re: #451). 
- [x] Check that the Lane isn't a single integer, as there will be duplication issues. More discussion here (RE: https://github.com/mskcc/vaporware/pull/442). Duplicate lane IDs checked for in #493.

This might be duplicate with other issues, but I didn't find any fit for this.
