### ISSUE TITLE
Overview of Project PCAWG_SV

### ISSUE THREAD

**Issue by gongyixiao** [mskcc/tempo#848]
# Overview:
The individual steps of the structural-variant classification pipeline are outlined below and detailed in the subsequent subsections:
1.  computing the exact breakpoint coordinates from clipped reads; 
2. removing redundant ‘segment-bypassing’ structural variants; 
3. merging rearrangement breakpoints with copy-number data to yield structural-variant breakpoint-demarcated, normalized, absolute copy-number data; 
4. clustering individual structural variants into structural-variant clusters and footprints; 
5. heuristically refining structural-variant clusters and footprints; 
6. filtering artifactual fold-back-type structural variants with insufficient support; 
7. determining balanced overlapping breakpoints (this step is to distinguish very short templated insertions from mutually overlapping balanced breakpoints); 
8. computing rearrangement patterns and categories.

# From PCAWG paper:
“four variant callers were used to identify somatically acquired structural variants from matched tumour and germline whole genome sequencing data: SvABA (Broad pipeline), DELLY (DKFZ pipeline), BRASS (Sanger pipeline) and dRanger (Broad pipeline). These were merged into a final call set using a graph-based algorithm to identify overlapping breakpoint junctions across algorithms. Detailed visual inspection of structural-variant calls suggested that a simple approach of accepting all structural-variant calls made by two or more of the four algorithms gave the best trade-off between sensitivity and specificity.”

- PCAWG dockstore: https://dockstore.org/search?search=pcawg

- [x] #849 SvABA (Broad pipeline): https://dockstore.org/containers/registry.hub.docker.com/weischenfeldt/svaba_workflow

- [x] #850 Delly Workflow:
  - EMBL Orignal: https://dockstore.org/containers/registry.hub.docker.com/weischenfeldt/bric-embl_delly_workflow

  - DKFZ: https://dockstore.org/containers/quay.io/pancancer/pcawg-dkfz-workflow

- [x] #851 BRASS (Sanger pipeline): https://dockstore.org/containers/registry.hub.docker.com/sevenbridges/pcawg_sanger_sbg_modified/pcawg_sanger_vc_sbg_modified

- [x] dRanger (Broad pipeline, Not publicly available yet): https://software.broadinstitute.org/cancer/cga/dranger

- [x] #852 PCAWG workflow to merge SVs from Sanger (BRASS), Broad Inst (DRanger & SnowMan) and EMBL/DKFZ (DELLY): 
https://hub.docker.com/r/weischenfeldt/pcawg_sv_merge

- [x] #853 The code for grouping structural variants into structural-variant clusters and footprints (Version 1.0) is available at： https://github.com/cancerit/ClusterSV

# References:
PCAWG SV [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7025897/) and [supplement](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7025897/bin/41586_2019_1913_MOESM1_ESM.pdf) here
